version: "3.8"

services:
  gitea:
    build:
      context: ./gitea
  ctfd:
    build:
      context: ./ctfd
    volumes:
      - ./tmp-ctfd:/opt/CTFd
  jenkins_agent:
    build:
      context: ./jenkins-agent
  localstack:
    ports:
      - "4510-4559:4510-4559"  # external service port range
      - "4566:4566"            # LocalStack Edge Proxy
  lighttpd:
    build:
      context: ./lighttpd
    container_name: lighttpd


  
  

