version: "3.8"

networks:
  jenkins:
    driver: bridge

services:
  jenkins_server:
    build:
      context: ./jenkins-server
    networks:
      - jenkins
    container_name: jenkins-server
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
  jenkins_agent:
    build:
      context: ./jenkins-agent
    container_name: jenkins-agent
    networks:
      - jenkins
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC33zkdtvwp8giZLp1mVUbqzCKi0KIiWD8/towT0+9k1SCDYjJ/YVPqKidkSefYaKBgJ1yFcWa9qroXAUd5nACXN3Xdes2fe4w+xZ8GQTpqHKyStEHy6R9QXi00r/VxGcmBYZWLifEyzV//PiRC+hUaG27JeeBnkZ1FEOyXUunpaPixNaDkfnLbCimflkd2uYH2arMY+FdOH950ezow/+v4vsNrzoMwVVCCSg/dIJBS2G/JaoAbbQgIGo63Kyz0j++rIInsXMFmxhy9hEpViX/tEorFzGh4gUvJPLy3IDjWjUz/Nfte9By6usQjN/1plJcuP+rUqrjjGeMpfhDP6aq5ZvfuPTmXOVkWJ9vJZaK2BCtSZk1vOJR4luxCyUZQbKgb3jS9YZ4N1ZS26z3EKwJGP/acNtEMx2u2zhY7zXdG7ca1Qo1yeVDMRctlvH++KMEYX/ZR6LqYlJyV6TFICZVUT7dLF65gq68UyIFswMu9pQ8/VvIMkkO6eiU1cqFr8gc=
  gitea:
    image: gitea/gitea:1.15.6
    container_name: Gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - jenkins
    volumes:
      - ./tmp-data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:22"
  ctfd:
    container_name: ctfd
    image: ctfd/ctfd:mark-3.3.1
    ports:
      - "8000:8000"
    networks:
      - jenkins
    volumes:
      - ./tmp-data/ctfd:/opt/CTFd

  
  

