version: 2.1

jobs:
  ci:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-docker-{{ .Branch }}
      - run:
          name: Load Docker layers cache
          command: |
            set +o pipefail
            docker load -i ~/docker-layers.tar | true
      - run:
          name: Docker compose
          command: |
            python3 prepare.py git
            cp -R ctfd/data/ tmp-ctfd/
            docker-compose -p cicd-goat -f docker-compose-dev.yaml up -d --build
      - run:
          name: Save Docker layers cache
          command: |
            DOCKER_IMAGES=$(docker images --format "{{ .Repository }}" --filter=reference="cicd-goat_*")
            DOCKER_LAYERS=$(for image in $DOCKER_IMAGES; do docker history $image -q | grep -v missing; done)
            docker save -o ~/docker-layers.tar $DOCKER_LAYERS
      - save_cache:
          key: v1-docker-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/docker-layers.tar
      - run:
          name: Install testing dependencies
          command: |
            python3 --version
            python3 -m pip install pipenv
            python3 -m pipenv install --deploy
      - run:
          name: Wait for services to start
          command: |
            for i in {1..30}
            do
              jenkins_status_code=$(curl --write-out %{http_code} --silent --output /dev/null localhost:8080/login) || true
              gitea_status_code=$(curl --write-out %{http_code} --silent --output /dev/null localhost:3000/) || true
              if [ "$jenkins_status_code" -eq 200 ] && [ "$gitea_status_code" -eq 200 ]; then
                break
              fi
              sleep 1
            done
            sleep 30
      - run:
          name: Pytest
          command: |
            pipenv run python -m pytest tests/
  release:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
    steps:
      - checkout
      - run:
          name: Build
          command: |
            pipenv run python -m pytest tests/


workflows:
  version: 2
  ci:
    jobs:
      - ci