version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Setup Python
          command: |
            python3 prepare.py git
            cp -R ctfd/data/ tmp-ctfd/
      - run:
          name: Docker compose
          command: docker-compose -f docker-compose-dev.yaml up -d
      - run:
          name: Install testing dependencies
          command: |
            python3 -m pip install pipenv
            pipenv install --deploy
      - run:
          name: Wait for services to start
          command: |
            while [ 1 ]
            do
              jenkins_status_code=$(curl --write-out %{http_code} --silent --output /dev/null localhost:8080/login) || true
              gitea_status_code=$(curl --write-out %{http_code} --silent --output /dev/null localhost:3000/) || true
              if [ "$jenkins_status_code" -eq 200 ] && [ "$gitea_status_code" -eq 200 ]; then
                break
              fi
              sleep 1
            done
            sleep 60
      - run:
          name: Pytest
          command: |
            pipenv run python -m pytest tests/
  release:
    docker:
      - image: cimg/<language>:<version TAG>
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the test job"


workflows:
  version: 2
  test:
    jobs:
      - test