on: [pull_request]

jobs:
  ci:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: cp -R data/ tmp-data/
      - name: Docker compose
        run: docker-compose -f docker-compose-dev.yaml up -d
      - name: Install testing dependencies
        run: pip install -r requirements.txt
      - name: Pytest
        run: pytest tests/




