on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: cp -R data/ tmp-data/
      - name: Docker compose
        run: docker-compose -f docker-compose-dev.yaml up -d
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install testing dependencies
        run: |
          python -m pip install pipenv
          python -m pipenv install --deploy
      - name: Wait for services to start
        run: |
          while [ 1 ]
          do
            jenkins_status_code=$(curl --write-out %{http_code} --silent --output /dev/null localhost:8080/login) || true
            gitea_status_code=$(curl --write-out %{http_code} --silent --output /dev/null localhost:3000/) || true
            if [ "$jenkins_status_code" -eq 200 ] && [ "$gitea_status_code" -eq 200 ]; then
              break
            fi
            sleep 1
          done
      - name: Pytest
        run: |
          pipenv run python -m pytest tests/






