on: [pull_request]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04, windows-latest, macos-10.15 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: cp -R data/ tmp-data/
      - name: Install Docker
        if: ${{ mattix.os == 'macos-10.15'}}
        run: brew install docker
      - name: Docker compose
        run: docker-compose -f docker-compose-dev.yaml up -d
      - name: Install testing dependencies
        run: pip install -i https://pypi.org/pypi -r requirements.txt
      - name: Pytest
        run: pytest tests/




