on:
  release:
    types: [published]

jobs:
  trigger-circleci-release:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI release
        run: curl -u "${{ secrets.CCI_TOKEN }}:" -d 'build_parameters[CIRCLE_JOB]=release' --data build_parameters[VERSION]=${{ github.event.release.tag_name }} https://circleci.com/api/v1.1/project/github/cider-security-research/cicd-goat/tree/main
