on:
  release:
    types: [published]

jobs:
  trigger-circleci-release:
    runs-on: ubuntu-latest
    env:
      REF: ${{ github.event.release.GITHUB_REF }}
      NAME: ${{ github.event.release.tag_name }}
    steps:
      - run: echo "$REF"
      - run: echo "$NAME"
      - name: Trigger CircleCI release
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0
        with:
          GHA_Meta: ${{ github.event.release.GITHUB_REF }}
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}