on:
  release:
    types: [published]

jobs:
  trigger-circleci-release:
    env:
      VERSION: ${{ github.event.release.GITHUB_REF }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI release
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0
        with:
          GHA_Meta: ${{ env.VERSION }}
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}