on: [release]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
      uses: actions/checkout@v2
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: |
          echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "ACCOUNT=cidersecurity" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build (version)
        run: |
          cd jenkins-server
          docker build --build-arg TAG=$VERSION -t $ACCOUNT/goat-jenkins-server:$VERSION .
          cd ..
          docker build --build-arg TAG=$VERSION -t $ACCOUNT/goat-jenkins-agent:$VERSION jenkins-agent.Dockerfile
          docker build --build-arg TAG=$VERSION -t $ACCOUNT/goat-gitea:$VERSION gitea.Dockerfile
          docker build --build-arg TAG=$VERSION -t $ACCOUNT/goat-ctfd:$VERSION ctfd.Dockerfile
      - name: Push (version)
        run: |
          docker push $ACCOUNT/goat-jenkins-server:$VERSION
          docker push $ACCOUNT/goat-jenkins-agent:$VERSION
          docker push $ACCOUNT/goat-gitea:$VERSION
          docker push $ACCOUNT/goat-ctfd:$VERSION
      - name: Push (latest)
        run: |
          docker tag $ACCOUNT/goat-jenkins-server:$VERSION $ACCOUNT/goat-jenkins-server:latest
          docker tag $ACCOUNT/goat-jenkins-agent:$VERSION $ACCOUNT/goat-jenkins-agent:latest
          docker tag $ACCOUNT/goat-gitea:$VERSION $ACCOUNT/goat-gitea:latest
          docker tag $ACCOUNT/goat-ctfd:$VERSION $ACCOUNT/goat-ctfd:latest
          docker push $ACCOUNT/goat-jenkins-server:$VERSION
          docker push $ACCOUNT/goat-jenkins-agent:$VERSION
          docker push $ACCOUNT/goat-gitea:$VERSION
          docker push $ACCOUNT/goat-ctfd:$VERSION







